### ISSUE TITLE
Rails 7?

### ISSUE THREAD

**Issue by davidlbean** [bobf/action_mailbox_amazon_ingress#14]
Hello - first, this is a super gem, and I'll enjoy it once I get it working.

Is it Rail 7 compatible?  I'm having issues getting it up and running, and I wonder if something has changed on SNS over the last couple of years...

* In the SNS subscription, should I have raw message deliver enabled or disabled?

If I enable it, the create method in the inbound_emails_controller will fail when verifying the signature because the structure of the SNS notification doesn't include the Signature Version field, so the SNS MessageVerifier fails.

If I disable it, the create method works as advertised, but the process method in my mailbox class can't find any values like the recipients or the email body.  I can get to the @incoming_email object within process(), but I don't see a way to get to the message body or addresses.  e.g ```mail['from']``` is nil.  And I noticed that the gem can't find the message ID either and generates a new one:  ```Message-ID couldn't be parsed or is missing. Generated a new Message-ID```.

I suspect I'm missing something obvious...

**Comment by davidlbean** [comment]
Aha...read the manual.  For anyone else who runs across this, here are my learnings:

* SNS has very different formats for that raw message flag, and for different reasons.  See the SNS Developer Guide for details, specifically:  https://docs.aws.amazon.com/sns/latest/dg/sns-large-payload-raw-message-delivery.html
* SNS will not deliver raw messages if they are over 150K -- such messages will be stored in S3 and you'll need to reach back into S3 to get them.

**Comment by bobf** [comment]
Hi, @davidlbean . Thank you for:

* Giving a thorough description of the problem.
* Trying various combinations of things to solve the issue.
* Figuring out the cause from the docs.
* Doing all of the above by the time I finished work. : )

@chrisortman extended my original [Rails PR](https://github.com/rails/rails/pull/39364) to handle the situation you've encountered. Although the PR is now nearly 4 years old, @ssunday recently took it upon themselves to try to get the PR merged, so you may find that this is available in mainline Rails relatively soon.

I'm afraid I am highly unlikely to extend this gem at this point but I would welcome a PR, however I think any efforts on this would be better focused on the Rails PR (or migrating the PR to `aws-sdk` or wherever it is best suited).

Thanks for your interest in this gem !

**Comment by ssunday** [comment]
@bobf @davidlbean I haven't e2e tested the PR with my changes to get CI working, so I need to do that (or someone needs to and report that it works) and figure out how to get Rails team to re-review the PR and hopefully merge it 🙏🏻

**Comment by ssunday** [comment]
@bobf @davidlbean Okay, as Rails closed the PR so I'll fork this repo and bring in the changes from the Rails PR into it and make a PR with it. 🙏🏻

**Comment by bobf** [comment]
@ssunday Such is life ! Thanks for being pragmatic about this and for the continued efforts, it's good to know the work done for the PR can still be put to good use. 

I'm away at a conference this week but will try to be responsive to any updates !

**Comment by ssunday** [comment]
@bobf Thank you for all your work on it over the years haha!

**Comment by mullermp** [comment]
@ssunday If you're willing to start a pull request, we could add this as a feature to aws-sdk-rails.

**Comment by ssunday** [comment]
@mullermp I already started working on bringing in the rails-PR changes into this repo's code 😅  and am almost done. Maybe one day I'll do that?

**Comment by ssunday** [comment]
Behold https://github.com/bobf/action_mailbox_amazon_ingress/pull/15

**Comment by mullermp** [comment]
It's up to you as a suggestion. aws-sdk-rails would give it wider audience and has other AWS - Rails integrations. @bobf mentioned you here https://github.com/rails/rails/pull/39364#issuecomment-2111669474

**Comment by ssunday** [comment]
@mullermp Yep, I am aware, and the project I needed this for for also uses aws-sdk-rails. It was just easier to bring it here to get the ball rolling for my project's needs. I don't have any issue about moving it to aws-sdk-rails—it just needs to be done and I don't know if/when I'll be able to.

**Comment by ssunday** [comment]
@mullermp Like you can port it over to, or anyone can, my goal was just to get the useful code in a place where projects could easily use it to get their AWS SES inbound connection working 😅

**Comment by ssunday** [comment]
@mullermp @bobf I started poking around doing it, but a hurdle I'm experiencing is related to the testing—minitest vs. rspec. I have some tests working/converted, but the request ones are painful and it feels like it'd make more sense to just convert to rspec, but that is also troublesome. I can open a super rough PR with what I have 🤷🏻

**Comment by mullermp** [comment]
Go ahead and open a pr to aws-sdk-rails and we can go from there. We prefer minitest for the rails part (I think it was simpler at the time?) although we use rspec in other products. We're not opposed to switching over.

**Comment by ssunday** [comment]
@mullermp Got it, I'll get a PR up.

**Comment by ssunday** [comment]
https://github.com/aws/aws-sdk-rails/pull/127
