### ISSUE TITLE
Possible changes upstream in SES

### ISSUE THREAD

**Issue by chrisortman** [bobf/action_mailbox_amazon_ingress#2]
https://github.com/bobf/action_mailbox_amazon_ingress/blob/9497e134dc3641378eb99f7a100ceafda5392338/app/controllers/action_mailbox/ingresses/amazon/inbound_emails_controller.rb#L119

Howdy, thanks for putting this gem together! I was grateful to find it when I realized SES had been pulled from Rails core.

I know you're working on getting this merged upstream, but just in case this can save you some headache down the road I wanted to let you know about something I ran into today.

When I am receiving the SNS notification the mail message is stored at `message['mail']` and not `message['content']`
Maybe there's a configuration I missed when setting it up? Seems like AWS shouldn't be changing these keys willy nilly.

**Comment by bobf** [comment]
@chrisortman Replying here as well as the Rails PR for completeness.

Are you sure you didn't enable raw message delivery ?

Check the documentation change here: https://github.com/rails/rails/commit/809f53b9576684a6fbd985d957ca22689d10138e

If you still think it's wrong then let me know and I'll take a look !

**Comment by chrisortman** [comment]
Yes. We can move discussion to rails pr
