### ISSUE TITLE
sync Rails PR with this repo?

### ISSUE THREAD

**Issue by michelson** [bobf/action_mailbox_amazon_ingress#3]
Hi, I'm interested to sync this library with the Rails PR code, that it seems it has more changes

does it makes any sense to you ? 
I don't know if the Rails PR will be merged soon so it might be a good idea, what you think ?

**Comment by bobf** [comment]
Hi, @michelson . I think that the Rails PR and this gem have diverged quite a lot so sync'ing them might be difficult. (e.g. this gem now has RSpec helpers which do not belong in Rails).

If there are specific features you wanted to copy into the PR then please describe what you would like to do and I would be happy to give you feedback/advice.
